apiVersion: apps/v1
kind: Deployment
metadata:
  name: carts
  labels:
    name: carts
    instance: carts
    component: service
    app: E-commerce-app
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      name: carts
      instance: carts
      component: service
      app: E-commerce-app
  template:
    metadata:
      labels:
        name: carts
        instance: carts
        component: service
        app: E-commerce-app
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
    spec:
      serviceAccountName: carts
      containers:
        - name: carts
          env:
            - name: JAVA_OPTS
              value: -XX:MaxRAMPercentage=75.0 -Djava.security.egd=file:/dev/urandom
          envFrom:
            - configMapRef:
                name: carts
          image: "public.ecr.aws/aws-containers/retail-store-sample-cart:0.5.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 45
            periodSeconds: 3
          resources:
            limits:
              memory: 512Mi
            requests:
              cpu: 128m
              memory: 512Mi
          volumeMounts:
            - mountPath: /tmp
              name: tmp-volume
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
            
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: carts-dynamodb
  labels:
    name: carts
    instance: carts
    component: dynamodb
    app: E-commerce-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: carts
      instance: carts
      component: dynamodb
      app: E-commerce-app
  template:
    metadata:
      labels:
        name: carts
        instance: carts
        component: dynamodb
        app: E-commerce-app
    spec:
      containers:
        - name: dynamodb
          image: "amazon/dynamodb-local:1.13.1"
          imagePullPolicy: IfNotPresent
          ports:
            - name: dynamodb
              containerPort: 8000
              protocol: TCP
