apiVersion: v1
kind: Service
metadata:
  name: carts-dynamodb
  labels:
   name: carts
   instance: carts
   component: dynamodb
   app: E-commerce-app
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: dynamodb
  selector:
    name: carts
    instance: carts
    component: dynamodb
    app: E-commerce-app

---

apiVersion: v1
kind: Service
metadata:
  name: carts
  labels:
    name: carts
    instance: carts
    component: service
    app: E-commerce-app
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
     name: carts
     instance: carts
     component: service
     app: E-commerce-app

---