apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
  labels:
    name: catalog
    instance: catalog
    component: service
    app: E-commerce-app
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      name: catalog
      instance: catalog
      component: service
      app: E-commerce-app
  template:
    metadata:
      labels:
        name: catalog
        instance: catalog
        component: service
        app: E-commerce-app
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
    spec:
      serviceAccountName: catalog
      containers:
        - name: catalog
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: catalog-db
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: catalog-db
                  key: password
            - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
              value: http://adot-collector.adot-collector-kubeprometheus:4317
          envFrom:
            - configMapRef:
                name: catalog
          image: "public.ecr.aws/aws-containers/retail-store-sample-catalog:0.5.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 3
          resources:
            limits:
              memory: 256Mi
            requests:
              cpu: 128m
              memory: 256Mi
          volumeMounts:
            - mountPath: /tmp
              name: tmp-volume
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory