apiVersion: v1
kind: Service
metadata:
  name: checkout-redis
  labels:
    name: checkout
    instance: checkout
    component: redis
    app: E-commerce-app
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis
  selector:
    name: checkout
    instance: checkout
    component: redis
    app: E-commerce-app

---

apiVersion: v1
kind: Service
metadata:
  name: checkout
  labels:
    name: checkout
    instance: checkout
    component: service
    app: E-commerce-app
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    name: checkout
    instance: checkout
    component: service
    app: E-commerce-app