apiVersion: v1
kind: Service
metadata:
  name: assets
  labels:
     name: assets
     instance: assets
     component: service
     app: E-commerce-app
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    name: assets
    instance: assets
    component: service
    app: E-commerce-app